### ISSUE TITLE
[Bug]: The eos_token of the Qwen 2.5 base model is inconsistent between config.json and tokenizer_config.json.

### ISSUE THREAD

**Issue by Songjw133** [QwenLM/Qwen2.5#927]
### Has this been raised before?

- [X] I have checked [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.
- [x] I confirm that this is not a bug report, a feature request, or a badcase.

### Description

![image](https://github.com/user-attachments/assets/af42b8b9-b81a-4d47-bdd4-edfd85b4ca24)
微调base模型的时候我发现输出无法停止，然后看了一下应该是结束符的问题。在config.json中，eos_token_id为151643，对应的应该是<|endoftext|>。但在tokenizer_config.json却是<|im_end|>。
![image](https://github.com/user-attachments/assets/06ef2500-13eb-448a-abad-ef27f3afb1bc)

**Comment by jeffchy** [comment]
same findings

**Comment by airstillblue** [comment]
请教一下，config.json里的"max_position_embeddings"是32k，这个值是不是不对，不应该是128k吗？

**Comment by jklj077** [comment]
Hi, all,

If you are unfamilar how `transformers` handles stopping criteria for text generation (the `model.generate` method), please first check out [its official documentation](https://huggingface.co/docs/transformers/main_classes/text_generation).

The configuration could be a bit confusing in `transformers` due to historical reasons. In short, at present, it is controlled by a bunch of stuff in the **`generation_config`** of the model, including `eos_token_id`, and its default values are in **`generation_config.json`**. Others are irrelevant.

As base models are not supposed to used for conversations, which is stated in the modelcard, you should use them without chat templates but with in-context examples for completion:
- The `eos_token_id` in the `generation_config.json` is thus set to `151643`, which is a sensible choice since it only knows this token.
- The `eos_token_id` in the `config.json` is deprecated in `transformers` but kept for backward compatibility.[^3p]
- The `eos_token` in the `tokenizer_config.json` should be `<|endoftext|>`; setting it to `<|im_end|>` is misleading for the base models, which has been fixed. [^3p]

If you have finetuned the based models, you need to set the stopping criteria in the `generation_config` accordingly:
- For example, if you use the ChatML template, you should set the **`eos_token_id`** to `[151643, 151645]`, which are `<|endoftext|>` and `<|im_end|>`. 
- As another example, if you use the Human/Assistant template, you should set the **`stop_strings`** to `["\n\nHuman:"]`.
- If, by any chance, you don't know which template you used, please seek help from relevant parties, e.g., who write that finetuning code.

You could also follow the `generation_config.json` in our instruct models to set other sampling parameters as well, e.g., `top_k`. However, we recommend adjusting those values for your usecase, since your finetuned models may behave differently from ours.

[^3p]: In general, third-party frameworks, e.g., `vllm`, do not follow the `generation_config` of `transformers`. It is advised to check their documentation. For example, `vllm` requires sampling parameters to be passed each time and it uses `eos_token_id` from the tokenizer, which corresponds to the `eos_token`.

**Comment by jklj077** [comment]
@airstillblue Glad you are asking about this! `max_position_embeddings` is set to 32K to keep innocent users from mistakingly using the models on long sequences. Please refer to the modelcard (e.g., [this](https://huggingface.co/Qwen/Qwen2.5-7B-Instruct#processing-long-texts)) of each model to see how to enable 128K context length. You can also check out [our documentation](https://qwen.readthedocs.io/zh-cn/latest/deployment/vllm.html#extended-context-support) on this.

**Comment by Songjw133** [comment]
> Hi, all,
> 
> If you are unfamilar how `transformers` handles stopping criteria for text generation (the `model.generate` method), please first check out [its official documentation](https://huggingface.co/docs/transformers/main_classes/text_generation).
> 
> The configuration could be a bit confusing in `transformers` due to historical reasons. In short, at present, it is controlled by a bunch of stuff in the **`generation_config`** of the model, including `eos_token_id`, and its default values are in **`generation_config.json`**. Others are irrelevant.
> 
> As base models are not supposed to used for conversations, which is stated in the modelcard, you should use them without chat templates but with in-context examples for completion:
> 
> * The `eos_token_id` in the `generation_config.json` is thus set to `151643`, which is a sensible choice since it only knows this token.
> * The `eos_token_id` in the `config.json` is deprecated in `transformers` but kept for backward compatibility.[1](#user-content-fn-3p-b06523f1cafabdf46aa58ecea3c4533d)
> * The `eos_token` in the `tokenizer_config.json` should be `<|endoftext|>`; setting it to `<|im_end|>` is misleading for the base models, which has been fixed. [1](#user-content-fn-3p-b06523f1cafabdf46aa58ecea3c4533d)
> 
> If you have finetuned the based models, you need to set the stopping criteria in the `generation_config` accordingly:
> 
> * For example, if you use the ChatML template, you should set the **`eos_token_id`** to `[151643, 151645]`, which are `<|endoftext|>` and `<|im_end|>`.
> * As another example, if you use the Human/Assistant template, you should set the **`stop_strings`** to `["\n\nHuman:"]`.
> * If, by any chance, you don't know which template you used, please seek help from relevant parties, e.g., who write that finetuning code.
> 
> You could also follow the `generation_config.json` in our instruct models to set other sampling parameters as well, e.g., `top_k`. However, we recommend adjusting those values for your usecase, since your finetuned models may behave differently from ours.
> 
> ## Footnotes
> 1. In general, third-party frameworks, e.g., `vllm`, do not follow the `generation_config` of `transformers`. It is advised to check their documentation. For example, `vllm` requires sampling parameters to be passed each time and it uses `eos_token_id` from the tokenizer, which corresponds to the `eos_token`. [↩](#user-content-fnref-3p-b06523f1cafabdf46aa58ecea3c4533d) [↩2](#user-content-fnref-3p-2-b06523f1cafabdf46aa58ecea3c4533d)

Thank you for your reply. I didn’t use chat templates. I manually added tokenizer.eos_token_id to the end of the input_ids when processing the fine-tuning data. The issue has been resolved after fixing tokenizer_config.json.

**Comment by LiweiPE** [comment]
> Hi, all,
> 
> If you are unfamilar how `transformers` handles stopping criteria for text generation (the `model.generate` method), please first check out [its official documentation](https://huggingface.co/docs/transformers/main_classes/text_generation).
> 
> The configuration could be a bit confusing in `transformers` due to historical reasons. In short, at present, it is controlled by a bunch of stuff in the **`generation_config`** of the model, including `eos_token_id`, and its default values are in **`generation_config.json`**. Others are irrelevant.
> 
> As base models are not supposed to used for conversations, which is stated in the modelcard, you should use them without chat templates but with in-context examples for completion:
> 
> * The `eos_token_id` in the `generation_config.json` is thus set to `151643`, which is a sensible choice since it only knows this token.
> * The `eos_token_id` in the `config.json` is deprecated in `transformers` but kept for backward compatibility.[1](#user-content-fn-3p-b06523f1cafabdf46aa58ecea3c4533d)
> * The `eos_token` in the `tokenizer_config.json` should be `<|endoftext|>`; setting it to `<|im_end|>` is misleading for the base models, which has been fixed. [1](#user-content-fn-3p-b06523f1cafabdf46aa58ecea3c4533d)
> 
> If you have finetuned the based models, you need to set the stopping criteria in the `generation_config` accordingly:
> 
> * For example, if you use the ChatML template, you should set the **`eos_token_id`** to `[151643, 151645]`, which are `<|endoftext|>` and `<|im_end|>`.
> * As another example, if you use the Human/Assistant template, you should set the **`stop_strings`** to `["\n\nHuman:"]`.
> * If, by any chance, you don't know which template you used, please seek help from relevant parties, e.g., who write that finetuning code.
> 
> You could also follow the `generation_config.json` in our instruct models to set other sampling parameters as well, e.g., `top_k`. However, we recommend adjusting those values for your usecase, since your finetuned models may behave differently from ours.
> 
> ## Footnotes
> 1. In general, third-party frameworks, e.g., `vllm`, do not follow the `generation_config` of `transformers`. It is advised to check their documentation. For example, `vllm` requires sampling parameters to be passed each time and it uses `eos_token_id` from the tokenizer, which corresponds to the `eos_token`. [↩](#user-content-fnref-3p-b06523f1cafabdf46aa58ecea3c4533d) [↩2](#user-content-fnref-3p-2-b06523f1cafabdf46aa58ecea3c4533d)

Hello, how about if I want to finetune base model to use as chat model? Should I set eos_token_id=<|im_end|> before finetuning? Because using base model when deploy in VLLM, causes repetition output even setting stop_words. Or can you briefly explain how you finetune the base to instruct model? Thanks!

**Comment by jklj077** [comment]
@LiweiPE To finetuning base models and get chat models, you need to adopt chat templates which tell the frameworks how should messages be formatted as texts. The eos_token, stop_strings, and such (names are different for different frameworks) are generally set according to the main chat template.

For Qwen2.5-Instruct models, we use the ChatML template, and you can reuse this template to finetune your own chat models. In that case, the eos_token should be set to "<|im_end|>" and it is better to finetune the embedding as well.

You can check the training framework mentioned in [the README](https://github.com/QwenLM/Qwen2.5#finetuning).

**Comment by chrisoutwright** [comment]
I had the case of following with qwen2.5:72b-instruct-q4_K_M 

![image](https://github.com/user-attachments/assets/97a69b9c-a0de-4bcc-9ca0-8d3d98a6967e)


It will ramble on without having asked this!!!

**Comment by jklj077** [comment]
is that Ollama? try adding the following to the Modelfile:
```
PARAMETER stop "<|im_end|>"
PARAMETER stop "<|endoftext|>"
PARAMETER stop "<|im_start|>"
```

**Comment by MattYoon** [comment]
I finetuned Qwen2.5 base using Axolotl, and it will never generate "<|im_end|>" and just generate gibberish afterwards. The same inference code (vanilla Transformers) works fine with Qwen2.5 Instruct, so it's not an issue with the inference code.

**Comment by jklj077** [comment]
if you used LoRA on Qwen2.5 base, see also https://github.com/QwenLM/Qwen2.5/issues/1064

**Comment by WayfarerYuan** [comment]
> if you used LoRA on Qwen2.5 base, see also #1064

How about using LoRA on Qwen 2.5 72B **Instruct**?

- I’m using LlamaFactory to fine-tune with LoRA.
- I’ve tried templates with either <|im_end|> or <endoftext|> as stop words (eos_token).
- However, in both cases, 10%–20% of the responses fail to stop correctly and end up repeating.
